apiVersion: v1
kind: Pod
metadata:
  name: postgres-client
  labels:
    app: postgres-client
spec:
  containers:
    - name: psql
      image: postgres:15
      command: ["sleep", "infinity"]
      env:
        - name: PGPASSWORD
          value: amatepass
      # You can exec into this pod and use psql to connect to your postgres service:
      # kubectl exec -it postgres-client -- psql -h postgres -U amateuser amatepos
